### ISSUE TITLE
Documentation for JTAG file format?

### ISSUE THREAD

**Issue by philtomson** [cambridgehackers/fpgajtag#1]
Is there any documentation for your .jtag file format?

**Comment by jankcorn** [comment]
We just use the standard .bit and .bin files as generated by xilinx tools.
Although there is not document for the .bit files, it is just a simple
prefix on a .bin file.
The .bin files are just sent as a byte stream to the h/w.  (they can be
decoded for understanding the fpga bitstream, but not necessary for
programming)

**Comment by philtomson** [comment]
Hmm... ok, so the *.jtag files in the testdata directory are just .bit files that that aren't in binary format? (would that be the correct interpretation?)

Oh, and also after poking around a bit, I'm guessing you dump the files to the .jtag format from your dump util? And then you can use fpgajtag -c <some.jtag> to read in the jtag file again (processed in process_command_list)? (I'm not entirely understanding the intent of process_command_list just yet)

Let me explain what I'm trying to do: I've got a BSCANE2 primitive instantiated in a Xilinx 7 Series part (on the KC705 board) and I've connected it up to a shift register. The idea is that if I go into the USER1 instruction I should be able to shift in data on the JTAG port and have it shift into my shift register (which feeds certain parameters of my design in the FPGA). 

I was thinking that either: 
1) I could make use of most of your code, but make some modifications such that I can just generate some data instead of reading a .bit file - and generate data that would appropriately force the JTAG controller on the Xilinx part into the USER1 mode so it would shift into my onboard shift reg... 

OR:

2) I could create a .jtag file that would do all of this for me without changing any of your code.

(I'm not sure yet which would be easier - anyway, hence the question about the .jtag format)

**Comment by jankcorn** [comment]
Aha....
You are going in the same direction I was attempting.  Sadly, I was trying
to do this on a Mac and having lots of issues with reliability using
libusb/ftdi/etc.   (getting bogus timeout responses)
Because of these problems, I left the support only partially completed.

So....
I would recommend continuing with the '-c' ascii command file (possibly
generated by another program).  If you need to have something more dynamic,
it should be easy to implement '-' as an input filename and take input from
stdin (so you can interact with the logic in realtime).

BTW, when I did the same thing with the KC705, I had some weird behavior
with only being able to use USER3 being mapped to be the same as USER1 and
USER4 being identical to USER2. (IIRC)

Also, I don't know if you have already successfully hooked up your logic to
the BSCANE2, but you might (possibly) find this useful:

https://github.com/cambridgehackers/connectal/blob/master/lib/bsv/Bscan.bsv
I expect you aren't using Bluespec, but the logic itself will probably
still be readable.

I apologize for the fuzzy answer... it has been a while and I am trying to
reconstruct 'what works/what doesn't'.

I hope you are able to make progress! :-)
jca

**Comment by gardners** [comment]
Did you get anywhere with this? I would love to be able to do a simple stink-normal boundary scan of the connected FPGA board, but can't (yet) figure out how the JTAG code is actually working, in terms of forming the JTAG command and dispatching it. I've been looking at read_idcode() for a couple of hours, and still can't figure out where the 001001 command is being sent.  I'll log a separate issue describing more clearly what I am trying to do...
