### ISSUE TITLE
Explanation of how fpgajtag actually forms JTAG commands

### ISSUE THREAD

**Issue by gardners** [cambridgehackers/fpgajtag#3]
I'm trying to adapt fpgajtag to do simple boundary scans on Xilinx FPGAs, since there seems to be no good alternatives: Vivado seems to lack a simple means of connecting to an FPGA and extracting the boundary scan (or is so complicated, that I can't find out how to do it) and seems to hang on some connections, and OpenOCD seems to be able to do just about everything with JTAG, except for simple boundary scans.  fpgajtag, in contrast, is beautifully simple, and never hangs the way Vivado does for me.  My only challenge is to understand the code enough to be able to adapt it to my purposes.

I've been looking at read_idcode() as what should be a simple JTAG transaction that is in many ways similar to doing a boundary scan. However, I can't for the life of me figure out how it actually works to send the JTAG command.  My understanding is that the JTAG command for IDCODE is 001001, but I see nothing suggestive of this in read_idcode().

What I would love, is to be able to craft something like the following (taken from https://www.fpga4fun.com/JTAG4.html) to be able to easily build JTAG transactions in the fpgajtag code base:

```
// go to reset state
  for(i=0; i<5; i++) JTAG_clock(TMS);

  // go to Shift-IR
  JTAG_clock(0);
  JTAG_clock(TMS);
  JTAG_clock(TMS);
  JTAG_clock(0);
  JTAG_clock(0);

  // Assuming that IR is 10 bits long,
  // that there is only one device in the chain,
  // and that SAMPLE code = 0000000101b
  JTAG_clock(1);
  JTAG_clock(0);
  JTAG_clock(1);
  JTAG_clock(0);
  JTAG_clock(0);
  JTAG_clock(0);
  JTAG_clock(0);
  JTAG_clock(0);
  JTAG_clock(0);
  JTAG_clock(0 or TMS);  // last bit needs to have TMS active, to exit shift-IR

  // we are in Exit1-IR, go to Shift-DR
  JTAG_clock(TMS);
  JTAG_clock(TMS);
  JTAG_clock(0);
  JTAG_clock(0);

  // read the boundary-scan chain bits in an array called BSB
  JTAG_read(BSB, 339);
  printf("Status of pin 99 = %d\n, BSB[3]);

```

Any pointers for how I would go about constructing such a sequence using the fpgajtag infrastructure? 

Thanks,
Paul.

**Comment by jameyhicks** [comment]
I'm afraid I don't understand the code either, but maybe we can get some clarification from the author.

My understanding is that this code precisely reproduces the transitions that vivado uses to program the FPGAs. So it's a bit more idiomatic.

This FTDI document might be helpful:
https://www.ftdichip.com/Support/Documents/AppNotes/AN_135_MPSSE_Basics.pdf
along with this one:
https://www.ftdichip.com/Support/Documents/AppNotes/AN_108_Command_Processor_for_MPSSE_and_MCU_Host_Bus_Emulation_Modes.pdf

**Comment by gardners** [comment]
Thanks. I'll take a look.

**Comment by jankcorn** [comment]
Paul,

I am the author of fpgajtag.
I will try to answer the questions as best I can.  If you have more
questions, please keep asking!

For starters:
1) Yes, the idcode command is indeed 001001.  This is in the file fpga.h as:
     #define IRREG_IDCODE      0x09
2) I originally started with a simple bit-twiddling command program
structure that you mentioned from 'www.fpga4fun.com/JTAG4.html' (a
long, long time ago).  The problem was that it is just too slow.
IIRC, programming something like a Virtex part could easily take 20-30
minutes.
To get programming speeds similar to the Xilinx Impact tool, we use
the FTDI chip MPSSE mode, which supports byte width interfaces to
TDO/TDI/TMS (and TCLK generated inside the FTDI chip):
    http://www.ftdichip.com/Documents/AppNotes/AN2232C-01_MPSSE_Cmnd.pdf
3) If you are more interested in learning how to make a simple JTAG
interface (along the lines you suggest) and avoid the complexity of
the MPSSE command structure, I would also be quite willing to help
with questions.
4) If you decide to build up a simple JTAG interface from scratch,
please copy the calls to 'pulse_gpio()'.  These control the wires from
the on-board FTDI chip to the Xilinx part itself (on Xilinx eval
boards).  In addition to the JTAG pins TCLK/TDO/TDI/TMS, there is also
a 'reset' wire for putting the Xilinx part into a 'known state'.
5) Another interface approach is possible by explicitly
writing/reading IR and DR registers.
Example files for this are in the 'testdata' directory.  The 'fast'
FTDI interface is used, but you have full access to all instruction
(IR) and data (DR) registers.  I used this for read/write of the BSCAN
interface in a Xilinx design.

Does this help?
jca

**Comment by gardners** [comment]
Ok. I managed to figure it out.  See https://github.com/MEGA65/mega65-core/blob/unstable/src/tools/fpgajtag/boundary_scan.c for details of how I did it.  My code is all GPL, so if you feel inclined to add any boundary scan stuff to fpgajtag, feel free to use it it's of any use.  More info here: https://c65gs.blogspot.com/2020/01/programming-bitstream-boot-flash.html

**Comment by jankcorn** [comment]
Nice code, thanks for sharing!
jca

**Comment by gardners** [comment]
I've been working further on it, so that it can even be used to monitor signals in realtime, like a cheap and cheery chipscope.  Surprisingly can already do close to 1KHz.
